//
//  Application+Sample.swift
//  code-interview-ios-itunes-search
//
//  Created by Martin on 2023/08/24.
//

import Foundation

extension Application {
    static let sample: Self = Application(id: 1,
                                          title: "피트니스",
                                          description: "This is a sample",
                                          sellerName: "Seller",
                                          iconUrl: "https://is4-ssl.mzstatic.com/image/thumb/Purple126/v4/b5/56/85/b5568559-f8ca-ec1e-aeb3-2166029daee6/AppIcon-0-0-1x_U007emarketing-0-0-0-10-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/100x100bb.jpg",
                                          url: "https://apps.apple.com/kr/app/%ED%94%BC%ED%8A%B8%EB%8B%88%EC%8A%A4/id1208224953?uo=4",
                                          screenshotUrls: [
                                            "https://is5-ssl.mzstatic.com/image/thumb/PurpleSource124/v4/21/eb/7e/21eb7e74-2cb5-908c-e46b-0c95b60fbf36/71d7e1ed-2f45-4687-8efc-ebd0308d5b43_1_1242x2208bb.png/392x696bb.png",
                                            "https://is2-ssl.mzstatic.com/image/thumb/PurpleSource124/v4/34/76/8b/34768b1d-6906-f792-5b9e-5b78200702eb/12ad3355-4c8c-4d83-ad9a-f03890b628b2_2_1242x2208bb-2.png/392x696bb.png"
                                          ],
                                          ipadScreenshotUrls: [
                                            "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource115/v4/ef/a8/74/efa874cc-724d-3eba-6119-404b29fe6858/fe150a84-676b-4343-b161-12ae6a52512c_12.9_iPad_Pro_Fitness_1.PNG/552x414bb.png",
                                            "https://is3-ssl.mzstatic.com/image/thumb/PurpleSource125/v4/7a/d0/2c/7ad02cb5-da61-a395-a2f2-98248307b428/639ab713-edb6-404e-92a1-24eade9051e5_12.9_iPad_Pro_Fitness_2.PNG/552x414bb.png",
                                            "https://is5-ssl.mzstatic.com/image/thumb/PurpleSource115/v4/4c/93/b7/4c93b7b9-5561-9db6-ff6d-3737f5a49ed4/e994cc88-7b2d-4826-a433-d342e448719b_12.9_iPad_Pro_Fitness_3.PNG/552x414bb.png"
                                          ],
                                          appleTvScreenshotUrls: [],
                                          primaryGenreName: "건강 및 피트니스",
                                          genres: ["건강 및 피트니스"],
                                          languages: [
                                            "AR",
                                            "CA",
                                            "HR",
                                            "CS",
                                            "DA",
                                            "NL",
                                            "EN",
                                            "FI",
                                            "FR",
                                            "DE",
                                            "EL",
                                            "HE",
                                            "HI",
                                            "HU",
                                            "ID",
                                            "IT",
                                            "JA",
                                            "KO",
                                            "MS",
                                            "NB",
                                            "PL",
                                            "PT",
                                            "RO",
                                            "RU",
                                            "ZH",
                                            "SK",
                                            "ES",
                                            "SV",
                                            "TH",
                                            "ZH",
                                            "TR",
                                            "UK",
                                            "VI"
                                         ],
                                          fileSizeBytes: "2530304",
                                          contentAdvisoryRating: "4+",
                                          averageUserRating: 3.283220000000000027284841053187847137451171875,
                                          userRatingCount: 286,
                                          version: "1.4",
                                          releaseNotes: "Bug Fixes and Feature Enhancements",
                                          currentVersionReleaseDate: Date.now,
                                          minimumOsVersion: "11.0",
                                          supportedDevices: [
                                            "iPhone5s-iPhone5s",
                                            "iPadAir-iPadAir",
                                            "iPadAirCellular-iPadAirCellular",
                                            "iPadMiniRetina-iPadMiniRetina",
                                            "iPadMiniRetinaCellular-iPadMiniRetinaCellular",
                                            "iPhone6-iPhone6",
                                            "iPhone6Plus-iPhone6Plus",
                                            "iPadAir2-iPadAir2",
                                            "iPadAir2Cellular-iPadAir2Cellular",
                                            "iPadMini3-iPadMini3",
                                            "iPadMini3Cellular-iPadMini3Cellular",
                                            "iPodTouchSixthGen-iPodTouchSixthGen",
                                            "iPhone6s-iPhone6s",
                                            "iPhone6sPlus-iPhone6sPlus",
                                            "iPadMini4-iPadMini4",
                                            "iPadMini4Cellular-iPadMini4Cellular",
                                            "iPadPro-iPadPro",
                                            "iPadProCellular-iPadProCellular",
                                            "iPadPro97-iPadPro97",
                                            "iPadPro97Cellular-iPadPro97Cellular",
                                            "iPhoneSE-iPhoneSE",
                                            "iPhone7-iPhone7",
                                            "iPhone7Plus-iPhone7Plus",
                                            "iPad611-iPad611",
                                            "iPad612-iPad612",
                                            "iPad71-iPad71",
                                            "iPad72-iPad72",
                                            "iPad73-iPad73",
                                            "iPad74-iPad74",
                                            "iPhone8-iPhone8",
                                            "iPhone8Plus-iPhone8Plus",
                                            "iPhoneX-iPhoneX",
                                            "iPad75-iPad75",
                                            "iPad76-iPad76",
                                            "iPhoneXS-iPhoneXS",
                                            "iPhoneXSMax-iPhoneXSMax",
                                            "iPhoneXR-iPhoneXR",
                                            "iPad812-iPad812",
                                            "iPad834-iPad834",
                                            "iPad856-iPad856",
                                            "iPad878-iPad878",
                                            "Watch4-Watch4",
                                            "iPadMini5-iPadMini5",
                                            "iPadMini5Cellular-iPadMini5Cellular",
                                            "iPadAir3-iPadAir3",
                                            "iPadAir3Cellular-iPadAir3Cellular",
                                            "iPodTouchSeventhGen-iPodTouchSeventhGen",
                                            "iPhone11-iPhone11",
                                            "iPhone11Pro-iPhone11Pro",
                                            "iPadSeventhGen-iPadSeventhGen",
                                            "iPadSeventhGenCellular-iPadSeventhGenCellular",
                                            "iPhone11ProMax-iPhone11ProMax",
                                            "iPhoneSESecondGen-iPhoneSESecondGen",
                                            "iPadProSecondGen-iPadProSecondGen",
                                            "iPadProSecondGenCellular-iPadProSecondGenCellular",
                                            "iPadProFourthGen-iPadProFourthGen",
                                            "iPadProFourthGenCellular-iPadProFourthGenCellular",
                                            "iPhone12Mini-iPhone12Mini",
                                            "iPhone12-iPhone12",
                                            "iPhone12Pro-iPhone12Pro",
                                            "iPhone12ProMax-iPhone12ProMax",
                                            "iPadAir4-iPadAir4",
                                            "iPadAir4Cellular-iPadAir4Cellular",
                                            "iPadEighthGen-iPadEighthGen",
                                            "iPadEighthGenCellular-iPadEighthGenCellular",
                                            "iPadProThirdGen-iPadProThirdGen",
                                            "iPadProThirdGenCellular-iPadProThirdGenCellular",
                                            "iPadProFifthGen-iPadProFifthGen",
                                            "iPadProFifthGenCellular-iPadProFifthGenCellular",
                                            "iPhone13Pro-iPhone13Pro",
                                            "iPhone13ProMax-iPhone13ProMax",
                                            "iPhone13Mini-iPhone13Mini",
                                            "iPhone13-iPhone13",
                                            "iPadMiniSixthGen-iPadMiniSixthGen",
                                            "iPadMiniSixthGenCellular-iPadMiniSixthGenCellular",
                                            "iPadNinthGen-iPadNinthGen",
                                            "iPadNinthGenCellular-iPadNinthGenCellular",
                                            "iPhoneSEThirdGen-iPhoneSEThirdGen",
                                            "iPadAirFifthGen-iPadAirFifthGen",
                                            "iPadAirFifthGenCellular-iPadAirFifthGenCellular",
                                            "iPhone14-iPhone14",
                                            "iPhone14Plus-iPhone14Plus",
                                            "iPhone14Pro-iPhone14Pro",
                                            "iPhone14ProMax-iPhone14ProMax",
                                            "iPadTenthGen-iPadTenthGen",
                                            "iPadTenthGenCellular-iPadTenthGenCellular",
                                            "iPadPro11FourthGen-iPadPro11FourthGen",
                                            "iPadPro11FourthGenCellular-iPadPro11FourthGenCellular",
                                            "iPadProSixthGen-iPadProSixthGen",
                                            "iPadProSixthGenCellular-iPadProSixthGenCellular"
                                         ])
}
