//
//  Application+Sample.swift
//  code-interview-ios-itunes-search
//
//  Created by Martin on 2023/08/24.
//

import Foundation

extension Application {
    static let sample: Self = Application(id: 1,
                                          title: "피트니스",
                                          description: "활동 세부사항, 운동 및 마음 챙기기 기록, 추세, 배지, Apple Watch 사용자를 위한 Apple Fitness+, 가족 및 친구와 공유 등 사용자의 피트니스에 관한 종합적인 정보를 파악하고 하나의 앱에 모아서 편리하게 볼 수 있습니다.\n\n기능\n\n• 간결한 요약 탭에서 활동 세부사항, 운동 및 마음 챙기기 기록, 추세 및 배지를 손쉽게 볼 수 있습니다.\n• 목표를 설정한 다음 하루 동안 진행 상황을 확인할 수 있습니다.\n• 움직이기 링을 사용하여 움직이기 목표를 향한 예상 소모 칼로리에 대한 세부사항을 볼 수 있습니다.\nApple Watch를 사용하면 운동하기 링에 대한 총 운동 시간과 일어서기에 대한 일어서기 시간을 볼 수 있습니다.\n• Apple Watch의 운동 앱 또는 타사 피트니스 앱에서 운동 기록을 볼 수 있습니다. 평균 페이스, 거리, 소모한 칼로리 등과 같은 각 운동에서 중요한 수치를 볼 수 있습니다.\n• 공유 탭에서 친구의 진행 상황을 보고 겨루기를 시작할 수 있습니다.\n• 또한 활동 링을 완성하는 진행 상황을 보고 Apple Watch의 활동 앱에서 총 걸음 수 및 거리와 같은 하루 동안의 활동 수치, 더 나아가 지난 운동과 명상을 볼 수 있습니다.\n\nApple Fitness+\n\nApple Watch 사용자는 Apple Fitness+를 구독하여 체력 수준에 상관없이 모두에게 적합한 다양한 피트니스로 건강한 일상을 경험할 수 있습니다. Apple Watch를 사용하면 화면에서 바로 심박수와 같은 실시간 수치를 볼 수 있습니다.\n\nApple Fitness+는 iPhone, iPad 및 Apple TV의 피트니스 앱에서 사용할 수 있으며 언제 어디서나 운동을 한 단계 높일 수 있습니다.\n\n기능\n\n• 강력한 동기를 부여하면서 모두를 포용하는 세계적인 트레이너의 어떠한 운동 기구도 필요 없는 운동과 명상 영상을 프리미엄 4K UHD(초고화질)로 5~45분 동안 감상할 수 있습니다.\n• 화면상에 표시되는 강도 및 경사 등에 관해 타이머, 트레이너 지침 및 코칭 방법을 볼 수 있습니다. 더 나아가, Apple Watch가 있는 경우 운동하면서 화면 오른쪽에 표시되는 소모한 칼로리, 심박수 등의 개인 활동 수치를 볼 수 있습니다.\n• 나의 운동 루틴의 분위기 및 에너지와 완벽하게 어울리도록 엄선된 음악뿐만 아니라 한 명의 아티스트의 전체 플레이리스트가 포함된 Artist Spotlight 시리즈도 즐길 수 있습니다.\n• 전 세계에서 가장 흥미롭고 영감을 주는 사람들과 함께 걸을 수 있는 특별한 오디오 운동인 ‘걷기 시간’을 사용할 수 있습니다. 그들은 자신의 이야기, 사진 및 노래를 공유하여 끊임없는 동기 부여를 통해 더 자주 걷도록 격려합니다.\n• 또한 ‘달리기 시간’에 접속하면 미국 및 해외로 이동하여 Apple Fitness+ 트레이너의 시선으로 역사적인 달리기 경로를 경험할 수 있습니다.\n• 초보자, 임산부, 노인을 대상으로 특수 제작된 사용자 설정 운동과 명상 프로그램을 만나볼 수 있습니다. 그리고 운동과 명상 모음이 첫 5킬로미터를 뛰거나 더 나은 수면을 위해 긴장을 푸는 등의 목표를 달성하도록 큐레이트되었습니다.\n• 트레이너, 시간, 음악 및 운동 기구로 운동과 명상을 필터링할 수 있습니다.\n• 새로운 구독자는 1개월 동안 무료로 체험할 수 있고, 이후에는 현재 기준으로 현지 가격이 매월 결제됩니다. 하나의 구독으로 6명의 가족 구성원이 이용할 수 있습니다. 하나의 저렴한 월별 요금제로 Apple Fitness+를 5개의 다른 훌륭한 서비스와 같이 사용하면 더 적은 비용으로 더 많은 서비스를 즐길 수 있습니다. 취소할 때까지 요금제가 자동으로 갱신됩니다. 약관이 적용됩니다. 계정 설정으로 이동한 다음 자동 갱신을 꺼서 언제든지 취소할 수 있습니다.\n\n*Apple Fitness+는 일부 지역에서만 사용할 수 있습니다.",
                                          sellerName: "Seller",
                                          iconUrl: "https://is4-ssl.mzstatic.com/image/thumb/Purple126/v4/b5/56/85/b5568559-f8ca-ec1e-aeb3-2166029daee6/AppIcon-0-0-1x_U007emarketing-0-0-0-10-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/100x100bb.jpg",
                                          url: "https://apps.apple.com/kr/app/%ED%94%BC%ED%8A%B8%EB%8B%88%EC%8A%A4/id1208224953?uo=4",
                                          screenshotUrls: [
                                            "https://is5-ssl.mzstatic.com/image/thumb/PurpleSource124/v4/21/eb/7e/21eb7e74-2cb5-908c-e46b-0c95b60fbf36/71d7e1ed-2f45-4687-8efc-ebd0308d5b43_1_1242x2208bb.png/392x696bb.png",
                                            "https://is2-ssl.mzstatic.com/image/thumb/PurpleSource124/v4/34/76/8b/34768b1d-6906-f792-5b9e-5b78200702eb/12ad3355-4c8c-4d83-ad9a-f03890b628b2_2_1242x2208bb-2.png/392x696bb.png"
                                          ],
                                          ipadScreenshotUrls: [
                                            "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource115/v4/ef/a8/74/efa874cc-724d-3eba-6119-404b29fe6858/fe150a84-676b-4343-b161-12ae6a52512c_12.9_iPad_Pro_Fitness_1.PNG/552x414bb.png",
                                            "https://is3-ssl.mzstatic.com/image/thumb/PurpleSource125/v4/7a/d0/2c/7ad02cb5-da61-a395-a2f2-98248307b428/639ab713-edb6-404e-92a1-24eade9051e5_12.9_iPad_Pro_Fitness_2.PNG/552x414bb.png",
                                            "https://is5-ssl.mzstatic.com/image/thumb/PurpleSource115/v4/4c/93/b7/4c93b7b9-5561-9db6-ff6d-3737f5a49ed4/e994cc88-7b2d-4826-a433-d342e448719b_12.9_iPad_Pro_Fitness_3.PNG/552x414bb.png"
                                          ],
                                          appleTvScreenshotUrls: [],
                                          primaryGenreName: "건강 및 피트니스",
                                          genres: ["건강 및 피트니스"],
                                          languages: [
                                            "AR",
                                            "CA",
                                            "HR",
                                            "CS",
                                            "DA",
                                            "NL",
                                            "EN",
                                            "FI",
                                            "FR",
                                            "DE",
                                            "EL",
                                            "HE",
                                            "HI",
                                            "HU",
                                            "ID",
                                            "IT",
                                            "JA",
                                            "KO",
                                            "MS",
                                            "NB",
                                            "PL",
                                            "PT",
                                            "RO",
                                            "RU",
                                            "ZH",
                                            "SK",
                                            "ES",
                                            "SV",
                                            "TH",
                                            "ZH",
                                            "TR",
                                            "UK",
                                            "VI"
                                         ],
                                          fileSizeBytes: "2530304",
                                          contentAdvisoryRating: "4+",
                                          averageUserRating: 3.283220000000000027284841053187847137451171875,
                                          userRatingCount: 286,
                                          version: "1.4",
                                          releaseNotes: "Bug Fixes and Feature Enhancements",
                                          currentVersionReleaseDate: Date.now,
                                          minimumOsVersion: "11.0",
                                          supportedDevices: [
                                            "iPhone5s-iPhone5s",
                                            "iPadAir-iPadAir",
                                            "iPadAirCellular-iPadAirCellular",
                                            "iPadMiniRetina-iPadMiniRetina",
                                            "iPadMiniRetinaCellular-iPadMiniRetinaCellular",
                                            "iPhone6-iPhone6",
                                            "iPhone6Plus-iPhone6Plus",
                                            "iPadAir2-iPadAir2",
                                            "iPadAir2Cellular-iPadAir2Cellular",
                                            "iPadMini3-iPadMini3",
                                            "iPadMini3Cellular-iPadMini3Cellular",
                                            "iPodTouchSixthGen-iPodTouchSixthGen",
                                            "iPhone6s-iPhone6s",
                                            "iPhone6sPlus-iPhone6sPlus",
                                            "iPadMini4-iPadMini4",
                                            "iPadMini4Cellular-iPadMini4Cellular",
                                            "iPadPro-iPadPro",
                                            "iPadProCellular-iPadProCellular",
                                            "iPadPro97-iPadPro97",
                                            "iPadPro97Cellular-iPadPro97Cellular",
                                            "iPhoneSE-iPhoneSE",
                                            "iPhone7-iPhone7",
                                            "iPhone7Plus-iPhone7Plus",
                                            "iPad611-iPad611",
                                            "iPad612-iPad612",
                                            "iPad71-iPad71",
                                            "iPad72-iPad72",
                                            "iPad73-iPad73",
                                            "iPad74-iPad74",
                                            "iPhone8-iPhone8",
                                            "iPhone8Plus-iPhone8Plus",
                                            "iPhoneX-iPhoneX",
                                            "iPad75-iPad75",
                                            "iPad76-iPad76",
                                            "iPhoneXS-iPhoneXS",
                                            "iPhoneXSMax-iPhoneXSMax",
                                            "iPhoneXR-iPhoneXR",
                                            "iPad812-iPad812",
                                            "iPad834-iPad834",
                                            "iPad856-iPad856",
                                            "iPad878-iPad878",
                                            "Watch4-Watch4",
                                            "iPadMini5-iPadMini5",
                                            "iPadMini5Cellular-iPadMini5Cellular",
                                            "iPadAir3-iPadAir3",
                                            "iPadAir3Cellular-iPadAir3Cellular",
                                            "iPodTouchSeventhGen-iPodTouchSeventhGen",
                                            "iPhone11-iPhone11",
                                            "iPhone11Pro-iPhone11Pro",
                                            "iPadSeventhGen-iPadSeventhGen",
                                            "iPadSeventhGenCellular-iPadSeventhGenCellular",
                                            "iPhone11ProMax-iPhone11ProMax",
                                            "iPhoneSESecondGen-iPhoneSESecondGen",
                                            "iPadProSecondGen-iPadProSecondGen",
                                            "iPadProSecondGenCellular-iPadProSecondGenCellular",
                                            "iPadProFourthGen-iPadProFourthGen",
                                            "iPadProFourthGenCellular-iPadProFourthGenCellular",
                                            "iPhone12Mini-iPhone12Mini",
                                            "iPhone12-iPhone12",
                                            "iPhone12Pro-iPhone12Pro",
                                            "iPhone12ProMax-iPhone12ProMax",
                                            "iPadAir4-iPadAir4",
                                            "iPadAir4Cellular-iPadAir4Cellular",
                                            "iPadEighthGen-iPadEighthGen",
                                            "iPadEighthGenCellular-iPadEighthGenCellular",
                                            "iPadProThirdGen-iPadProThirdGen",
                                            "iPadProThirdGenCellular-iPadProThirdGenCellular",
                                            "iPadProFifthGen-iPadProFifthGen",
                                            "iPadProFifthGenCellular-iPadProFifthGenCellular",
                                            "iPhone13Pro-iPhone13Pro",
                                            "iPhone13ProMax-iPhone13ProMax",
                                            "iPhone13Mini-iPhone13Mini",
                                            "iPhone13-iPhone13",
                                            "iPadMiniSixthGen-iPadMiniSixthGen",
                                            "iPadMiniSixthGenCellular-iPadMiniSixthGenCellular",
                                            "iPadNinthGen-iPadNinthGen",
                                            "iPadNinthGenCellular-iPadNinthGenCellular",
                                            "iPhoneSEThirdGen-iPhoneSEThirdGen",
                                            "iPadAirFifthGen-iPadAirFifthGen",
                                            "iPadAirFifthGenCellular-iPadAirFifthGenCellular",
                                            "iPhone14-iPhone14",
                                            "iPhone14Plus-iPhone14Plus",
                                            "iPhone14Pro-iPhone14Pro",
                                            "iPhone14ProMax-iPhone14ProMax",
                                            "iPadTenthGen-iPadTenthGen",
                                            "iPadTenthGenCellular-iPadTenthGenCellular",
                                            "iPadPro11FourthGen-iPadPro11FourthGen",
                                            "iPadPro11FourthGenCellular-iPadPro11FourthGenCellular",
                                            "iPadProSixthGen-iPadProSixthGen",
                                            "iPadProSixthGenCellular-iPadProSixthGenCellular"
                                         ])
}
